#!/bin/bash
#

OO_ROOT=`dirname $0`
EXOFS_DIR=$OO_ROOT/fs/exofs
USR_DIR=$OO_ROOT/usr
MOUNTDIR=/mnt/osd0
DEV_OSD=/dev/osd0
PID=0x10000
FORMAT_SIZE=0

MNT_PNFS=/mnt/pnfs

export LD_LIBRARY_PATH=$OO_ROOT/lib

do_cmd()
{
	$* 2>&1 | logger -t `basename $1` &
}

prompt()
{
	read -p "$* >>> "
}

start_exofs()
{
# 	insmod $EXOFS_DIR/exofs.ko
	modprobe exofs
# 	add-symbol-file $EXOFS_DIR/exofs.ko
}

stop_exofs()
{
# 	rmmod exofs
	modprobe --remove exofs
}

start_mount()
{
	OPT="pid=$PID,_netdev"

	mount -t exofs -o $OPT $DEV_OSD $MOUNTDIR
}

stop_mount()
{
	umount $MOUNTDIR
}

mkexofs_format()
{
	$USR_DIR/mkfs.exofs --pid=$PID --format=$FORMAT_SIZE $DEV_OSD
}

exofs_hello_world()
{
	echo hello > $MOUNTDIR/world
	cat $MOUNTDIR/world
}

do_pnfs_start()
{
	service nfs start

#	echo $((0x7fff)) > /proc/sys/sunrpc/nfs_debug
#	echo $((0x7fff)) > /proc/sys/sunrpc/nfsd_debug
	nfsdbg
	modprobe objlayoutdriver

# 	mount -t nfs4 -o minorversion=1 localhost:/ $MNT_PNFS
}

do_pnfs_stop()
{
	umount $MNT_PNFS
	modprobe --remove objlayoutdriver
	service nfs stop
}

cthon_test()
{
	cd /home/bharrosh/dev/git/pub/tests/cthon04-nfs41
	umount /mnt/localhost
	./server -a -p / localhost
}

dd_test()
{
	dd if=/dev/zero of=$MNT_PNFS/dd bs=4M count=1
}

case $1 in
start)
	echo $0 Starting | logger

	start_exofs
	start_mount

	echo $0 Initialized | logger
	;;

stop)
	echo $0 Stopping | logger

	stop_mount
	stop_exofs

	echo $0 Stopped | logger
	;;

restart)
	echo $0 restart | logger

	prompt stop_exofs
	stop_mount
	stop_exofs

	prompt start_exofs
	start_exofs
	start_mount

	echo $0 restart | logger
	;;

test)
	cthon_test
	;;

format)
	prompt mkexofs_format
	mkexofs_format
	echo $0 format | logger
	;;

format_start)
	echo $0 Starting | logger

	prompt start_exofs
	start_exofs

	prompt mkexofs_format
	mkexofs_format

	prompt start_mount
	start_mount

	prompt exofs_hello_world
	exofs_hello_world

	echo $0 format_start | logger
	;;

pnfs_start)
	do_pnfs_start
	echo $0 pnfs_start | logger
	;;

pnfs_stop)
	do_pnfs_stop
	echo $0 pnfs_stop | logger
	;;
esac
