#!/bin/bash
#

OO_ROOT=`dirname $0`
EXOFS_DIR=$OO_ROOT/fs/exofs
USR_DIR=$OO_ROOT/usr
MOUNTDIR=/mnt/osd0
PID=0x10000
FORMAT_SIZE=0

DEV_OSD0=/dev/osd0
UUID0="d2683732-c906-4ee1-9dbd-c10c27bb40df"

DEV_OSD1=/dev/osd1
UUID1="68b603b0-e438-43cb-8252-cd264c33dbcf"

MNT_PNFS=/mnt/pnfs

export LD_LIBRARY_PATH=$OO_ROOT/lib

do_cmd()
{
	$* 2>&1 | logger -t `basename $1` &
}

prompt()
{
	read -p "$* >>> "
}

start_exofs()
{
# 	insmod $EXOFS_DIR/exofs.ko
	modprobe exofs
# 	add-symbol-file $EXOFS_DIR/exofs.ko
}

stop_exofs()
{
# 	rmmod exofs
	modprobe --remove exofs
}

start_mount()
{
	OPT="pid=$PID,_netdev"

	mount -t exofs -o $OPT $DEV_OSD0 $MOUNTDIR
}

stop_mount()
{
	umount $MOUNTDIR
}

mkexofs_format()
{
	$USR_DIR/mkfs.exofs \
		--pid=$PID --raid=0 --mirrors=1\
		--dev=$DEV_OSD0 --format=$FORMAT_SIZE  --osdname=$UUID0 \
		--dev=$DEV_OSD1 --format=$FORMAT_SIZE  --osdname=$UUID1
}

exofs_hello_world()
{
	echo hello > $MOUNTDIR/world
	cat $MOUNTDIR/world
}

do_nfsdbg()
{
# 	nfsdbg
	echo $((0x1000)) > /proc/sys/sunrpc/nfs_debug
	echo $((0x7fff)) > /proc/sys/sunrpc/nfsd_debug
	echo "8 7 1 7" > /proc/sys/kernel/printk

# 	nfsdbg off
# 	echo $((0x0000)) > /proc/sys/sunrpc/nfs_debug
# 	echo $((0x0)) > /proc/sys/sunrpc/nfsd_debug
}

do_pnfs_start()
{
	if [ -z "$(df $MOUNTDIR |grep $DEV_OSD0)" ]; then
		start_exofs
		start_mount
	fi

	service nfs start

	modprobe objlayoutdriver

	mount -t nfs4 -o minorversion=1 localhost:/ $MNT_PNFS
}

do_pnfs_stop()
{
	umount $MNT_PNFS
	modprobe --remove objlayoutdriver
	service nfs stop
}

cthon_test()
{
	cd /home/bharrosh/dev/git/pub/tests/cthon04-nfs41
	umount /mnt/localhost
	./server -a -p / localhost
}

dd_test()
{
	# let in an IO for the grace period
	dd if=/dev/zero of=$MNT_PNFS/dd4 bs=4k count=512

	prompt "do truncate test"
	# start the test
	{
		for i in {1..10}; do
			echo $i;
			dd if=/dev/zero bs=4k count=512
			sleep 1;
		done > $MNT_PNFS/dd4 ;
		echo "===== T1 =====" ;
	} &

	{
		for i in {1..30}; do
			echo -n . ;
			echo b > $MOUNTDIR/dd4; sleep 0.33;
		done ;
		echo "===== T2 =====" ;
	} &
}
# dd if=/dev/zero of=/mnt/pnfs/dd seek=16 bs=4k count=512

case $1 in
start)
	echo $0 Starting | logger

	start_exofs
	start_mount

	echo $0 Initialized | logger
	;;

stop)
	echo $0 Stopping | logger

	stop_mount
	stop_exofs

	echo $0 Stopped | logger
	;;

restart)
	echo $0 restart | logger

	prompt stop_exofs
	stop_mount
	stop_exofs

	prompt start_exofs
	start_exofs
	start_mount

	echo $0 restart | logger
	;;

test)
	cthon_test
	;;

format)
	prompt mkexofs_format
	mkexofs_format
	echo $0 format | logger
	;;

format_start)
	echo $0 Starting | logger

	prompt start_exofs
	start_exofs

	prompt mkexofs_format
	mkexofs_format

	prompt start_mount
	start_mount

	prompt exofs_hello_world
	exofs_hello_world

	echo $0 format_start | logger
	;;

pnfs_start)
	do_pnfs_start
	echo $0 pnfs_start | logger
	;;

pnfs_stop)
	do_pnfs_stop
	echo $0 pnfs_stop | logger
	;;

pnfs_test)
	dd_test
	;;

nfsdbg)
	do_nfsdbg
	;;

esac
