#!/bin/sh
#
# how to load> gdb -e ./.build_um/vmlinux
# in gdb do> run ubd0=/usr0/var/local/um/Fedora7-AMD64-root_fs eth0=tuntap,,,192.168.0.117 mem=256M
# in gdb do> handle SIGUSR1 pass nostop noprint
# in gdb do> break sys_init_module (for loading .ko syboles
# in gdb do> add-symbol-file path-to-.ko-file addar from above ()
#

# OPEN_ISCSI=../open-iscsi
# iscsiadm=$OPEN_ISCSI/usr/iscsiadm
iscsiadm=iscsiadm
# ISCSI=iscsi
ISCSI=open-iscsi

# TODO: edit path to osd device
DEV_OSD=/dev/osd0

# TODO: Edit info of your target (only $IP_OSD is used)
#
# OSD 2 osc's osd-target
# SIM=tgtd
# IQN_OSD=bh-buildlin2.bhalevy.com
IP_OSD=192.168.0.142:3260	# buildlin2
# IP_OSD=192.168.0.241:3260	# testlin1
# IP_OSD=192.168.0.242:3260	# testlin2
# IP_OSD=10.64.1.132 		# pref-x4

# 0SD 1 IBM
# SIM=ibm-osd-sim
# IQN_OSD=iqn.2004-11.com.ibm:fb:bh-buildlin2.bhalevy.com
# IP_OSD=192.168.0.142:3261

do_cmd()
{
	$* 2>&1 | logger &
}

start_sim()
{
# FIXME: We want output to go to the other terminal we could
#	do less some_file in the other consul and rederect
#	here to some_file
	prompt "start target_simulator in other terminal"
}
stop_sim()
{
	prompt "Stop! target_simulator in other terminal"
}

start_iscsi_intiator()
{
# 	pushd $OPEN_ISCSI/
# 	do_cmd utils/iscsi-initiator start
# 	popd
# 
# 	until cat /sys/class/iscsi_transport/tcp/handle 2>/dev/null ; do
# 		sleep 1;
# 	done

	if ! service $ISCSI status; then
		do_cmd service $ISCSI start ;

		until cat /sys/class/iscsi_transport/tcp/handle 2>/dev/null ; do
			sleep 1;
		done
	fi
}

stop_iscsi_intiator()
{
# 	pushd $OPEN_ISCSI/
# 	do_cmd utils/iscsi-initiator stop
# 	popd

	do_cmd service $ISCSI stop

	until [ -n `modprobe -l scsi_transport_iscsi` ]; do
		sleep 1;
	done
}

start_open_osd()
{
# In-tree
	modprobe osd;
	until insmod ./drivers/scsi/osd/osd_ktests.ko; do sleep 1; done

# Out-of-tree
# 	until insmod ./drivers/scsi/osd/libosd.ko; do sleep 1; done
# 	until insmod ./drivers/scsi/osd/osd.ko; do sleep 1; done
# 	until insmod ./drivers/scsi/osd/osd_ktests.ko; do sleep 1; done
}
stop_open_osd()
{
# In-tree
	rmmod osd_ktests
	modprobe --remove osd;

# Out-of-tree
# 	rmmod osd_ktests
# 	rmmod osd
# 	rmmod libosd
}

# ISCSI_DBG=--debug=8
login_iscsi_osd()
{
	echo login into: $IP_OSD
	until $iscsiadm $ISCSI_DBG -m discovery -t sendtargets -p $IP_OSD --login; do 
		sleep 1; 
	done

	until ls $DEV_OSD 2>/dev/null; do sleep 1; done
}
logout_iscsi_osd()
{
	do_cmd $iscsiadm -m node -p $IP_OSD --logout

	while ls $DEV_OSD 2>/dev/null; do sleep 1; done
	sleep 1;
}

test_osd()
{
	./usr/osd_test --kernel=1 --usrlib=1 $DEV_OSD
# 	./usr/osd_test --kernel=0 --usrlib=1 $DEV_OSD
# 	./usr/osd_test --kernel=1 --usrlib=0 $DEV_OSD
}

do_osdblk()
{

# create
# 	usr/osdblk --create --pid=0x10017 --oid=0x10017 --length=100M /dev/osd0

# probe

# load_object
	modprobe osdblk
	echo $((0x10017)) $((0x10017)) /dev/osd0 > /sys/class/osdblk/add

# unload
# 	echo 0 > /sys/class/osdblk/remove

}

run_exofs()
{
	./do-exofs format_start
}

prompt()
{
	read -p "$* >>> "
}

case $1 in
stop)
	echo $0 Stopping | logger

	logout_iscsi_osd

	stop_iscsi_intiator

	stop_open_osd

# 	stop_sim

	echo $0 Stopped | logger
	;;

test)
	test_osd
	;;

osdblk)
	do_osdblk
	;;

login)
	login_iscsi_osd
	;;

logout)
	logout_iscsi_osd
	;;

*)
	echo $0 Starting | logger

# 	start_sim

	start_iscsi_intiator

	start_open_osd

	login_iscsi_osd

	prompt test_osd
	test_osd

	prompt run_exofs
	run_exofs

	echo $0 Initialized | logger
	;;
esac
